export const UPLOAD_REQUEST_REQUEST="UPLOAD_REQUEST_REQUEST";
 export const UPLOAD_REQUEST_SUCCESS="UPLOAD_REQUEST_SUCCESS";
 export const UPLOAD_REQUEST_FAILURE="UPLOAD_REQUEST_FAILURE";

 export const GET_BANNER_REQUEST="GET_BANNER_REQUEST";
 export const GET_BANNER_SUCCESS="GET_BANNER_SUCCESS";
 export const GET_BANNER_FAILURE="GET_BANNER_FAILURE";

 export const DELETE_BANNER_REQUEST="DELETE_BANNER_REQUEST";
 export const DELETE_BANNER_SUCCESS="DELETE_BANNER_SUCCESS"; 
 export const DELETE_BANNER_FAILURE="DELETE_BANNER_FAILURE";

 export const GET_SETTINGS_REQUEST = "GET_SETTINGS_REQUEST";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAILURE = "GET_SETTINGS_FAILURE";

export const UPDATE_SETTINGS_REQUEST = "UPDATE_SETTINGS_REQUEST";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const UPDATE_SETTINGS_FAILURE = "UPDATE_SETTINGS_FAILURE";
